### ISSUE TITLE
Stale socket can prevent plugin from starting

### ISSUE THREAD

**Issue by funkypenguin** [FalcoSuessgott/vault-kubernetes-kms#134]
We've been working on implementing vault-kubernets-kms into a bare-metal cluster, and it happens that one of the control-plane node has a hardware fault, and is restarting frequently.

On this node, we observed that when the plugins starts after a previously unexpected shutdown, crashes with an error about the socket already being in-use (`/opt/kms/vaultkms.socket`, in the default configuration)

Would it be possible to pass an argument to the plugin to overwrite a stale socket, rather than crash? In the current setup, it's possible that (for example) a power failure will take all the controlplane nodes down suddenly, and then the apiservers won't be able to restart on power restore, because the vault-kubernetes-kms isn't available due to the existing socket file :(

Thanks!
D

**Comment by FalcoSuessgott** [comment]
`vault-kubernetes-kms v0.3.0` ships with a `-force-socket-overwrite` (`FORCE_SOCKET_OVERWRITE`); default: `false` flag  :)
