### ISSUE TITLE
todos

### ISSUE THREAD

**Issue by FalcoSuessgott** [FalcoSuessgott/vault-kubernetes-kms#34]
- [x] draw architecture diagramm
- [x] add resource limits
- [x] add kms v1 e2e
- [ ] more testing
- [x] benchmark tests 
- [x] Kind quickstart vhs gif
- [x] Key rotation in e2e
- [x] Migrating docs
- [x] Better token renewal chexk from vault agent
- [x] Research max token ttl
- [x] Include encryption configs in docs
- [x] token creatoin orphaned and periodic in docs

**Comment by FalcoSuessgott** [comment]
add integrations for k3d, k3s, minikube, kubespray,. ...

**Comment by Babbili** [comment]
any chances we have the container image on a public registry please, or any reason not to
![image](https://github.com/user-attachments/assets/46449d19-e89e-40e7-a936-23aa759ef5c8)
